### ISSUE TITLE
Only brightness and state get retrieved (missing Color etc.)

### ISSUE THREAD

**Issue by floari** [home-assistant/scenegen#11]
Hi,

during my last attempts on using scenegen it stopped to capture the color from my bulbs (mixture of Tradfri and Hue on Hue hub - if that matters). Only state and brightness were retrieved. 
A few months ago it worked fine (I did a git pull yesterday before using scenegen).

Thanks!

**Comment by acockburn** [comment]
Given the information above, scenegen is working as expected. By default it expects to output color info using the "color_temp" attribute, and as you can see, color_temp is not in the info supplied to scenegen by HASS.  You need to pick another color tpye using the `-c` option,  for instance `-c rgb_color` and you will get the color information output. This is described in the docs, here:

https://www.home-assistant.io/docs/ecosystem/scenegen/#colors
