### ISSUE TITLE
Not getting it to work, Error

### ISSUE THREAD

**Issue by daaf84** [home-assistant/scenegen#12]
I get this error: 
```
Traceback (most recent call last):
  File "./scenegen.py", line 3, in <module>
    import requests
ImportError: No module named 'requests'
```

I run Hass.io and installed scenegen on an other Pi an run it with this command:

`~/scenegen$ ./scenegen.py https://192.168.1.10:8123 -k xxxxxxx`

**Comment by daaf84** [comment]
Appears that pip3 requests wasn't installed. 
Now I did, but have this output:

```
osmc@osmc:~/scenegen$ ./scenegen.py https://xxxxxx.duckdns.org -k xxxxxxx
name: My New Scene
entities:
```

So, it connects, but no entities are listed.... And yes, I've punt on some lights. ;)

**Comment by donkawechico** [comment]
Had the same problem as @daaf84. Fixed it by creating a long lived access token, and sending that token with the `-k` command-line option instead of the api_password.

**Comment by frenck** [comment]
Creating scenes from current states, is now a native feature of Home Assistant.
